AliasMatch "^/api/private/llamadas/v1/resultado$" "/var/www/html/api/private/llamadas/v1/resultado.php"

<Directory "/var/www/html/api/private">
    Options -Indexes
    AllowOverride None
    Require all granted
</Directory>

<Directory "/var/www/html/tests">
    Options -Indexes
    AllowOverride None
    Require all denied
</Directory>
